const DATA=window.KORAK_DATA,LESSONS=DATA.lessons,KEY="korak-v6",OLD_KEYS=["korak-v5","korak-a1-v3"],DAY=86400000,INTERVALS=[0,1,3,7,14,30,60,90];
let state=load(),active=null,queue=[],pos=0,answer="",checked=false,mode="lesson",session={correct:0,total:0,dialogues:0,reviews:0,start:0};
const $=s=>document.querySelector(s),lessonById=id=>LESSONS.find(l=>l.id===id),levelLessons=id=>LESSONS.filter(l=>l.level===id),chapterLessons=id=>LESSONS.filter(l=>l.chapterId===id&&!l.isTest);
function defaults(){return {xp:0,streak:1,bestStreak:1,completed:[],items:{},lastStudy:null,lastLesson:"a1-1-1",selectedLevel:"A1",total:0,correct:0,testStars:{},studySeconds:0,daily:{date:"",exercises:0,reviews:0,dialogues:0}}}
function load(){try{let cur=JSON.parse(localStorage.getItem(KEY)||"null");if(cur)return Object.assign(defaults(),cur);for(const k of OLD_KEYS){const old=JSON.parse(localStorage.getItem(k)||"null");if(old){const s=Object.assign(defaults(),old);if(k==="korak-a1-v3")s.completed=(old.completed||[]).map(n=>`a1-${Math.floor((n-1)/5)+1}-${((n-1)%5)+1}`).filter(lessonById);localStorage.setItem(KEY,JSON.stringify(s));return s}}}catch(e){}return defaults()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function resetDaily(){if(state.daily.date!==today())state.daily={date:today(),exercises:0,reviews:0,dialogues:0}}
function updateStreak(){const t=today();if(state.lastStudy===t)return;const y=new Date(Date.now()-DAY).toISOString().slice(0,10);state.streak=state.lastStudy===y?(state.streak||1)+1:1;state.bestStreak=Math.max(state.bestStreak||1,state.streak);state.lastStudy=t}
function norm(s){return String(s||"").trim().toLocaleLowerCase("hr").replace(/[.!?,;:„“"'…–—()]/g,"").replace(/\s+/g," ")}
function plain(s){return norm(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/dj|đ/g,"d")}
function itemKey(lid,i){return `${lid}-${i}`}
function st(k){return state.items[k]||{box:0,due:0,seen:0,correct:0,wrong:0}}
function schedule(k,ok){const s=st(k);s.seen++;if(ok){s.correct++;s.box=Math.min(INTERVALS.length-1,s.box+1)}else{s.wrong++;s.box=Math.max(0,s.box-2)}s.due=Date.now()+INTERVALS[s.box]*DAY;state.items[k]=s}
function learningLessons(){return LESSONS.filter(l=>!l.isTest)}
function due(){const out=[];learningLessons().forEach(l=>l.items.forEach((it,i)=>{const k=itemKey(l.id,i),s=st(k);if(s.seen&&s.due<=Date.now())out.push({...it,key:k,lessonId:l.id})}));return out}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function pool(field){return [...new Set(learningLessons().flatMap(l=>l.items.map(x=>x[field])))]}
function distract(cur,field){return shuffle(pool(field).filter(x=>x!==cur)).slice(0,3)}
function chapterUnlocked(chapter,index){if(index===0)return true;const lev=DATA.levels.find(x=>x.id===chapter.level),prev=lev.chapters[index-1];return state.completed.includes(prev.testId)}
function lessonUnlocked(lesson,chapter,index){if(!chapterUnlocked(chapter,index))return false;const all=LESSONS.filter(l=>l.chapterId===chapter.id),idx=all.findIndex(x=>x.id===lesson.id);return idx===0||state.completed.includes(all[idx-1].id)}
function isUnlocked(l){const lev=DATA.levels.find(x=>x.id===l.level),ci=lev.chapters.findIndex(c=>c.id===l.chapterId);return lessonUnlocked(l,lev.chapters[ci],ci)}
function nextLesson(){const list=levelLessons(state.selectedLevel||"A1");return list.find(l=>!state.completed.includes(l.id)&&isUnlocked(l))||list.find(isUnlocked)||list[0]}
function levelProgress(id){const list=levelLessons(id),done=list.filter(l=>state.completed.includes(l.id)).length;return {done,total:list.length,p:list.length?Math.round(done/list.length*100):0}}
function show(id){["home","levels","practice","profile","achievements","lesson","done"].forEach(v=>$("#"+v).classList.toggle("active",v===id));document.querySelectorAll(".bottomNav [data-screen]").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));if(id==="home")renderHome();if(id==="levels")renderLevels();if(id==="practice")renderPractice();if(id==="profile")renderProfile();if(id==="achievements")renderAchievements();scrollTo(0,0)}
function renderCommon(){resetDaily();$("#xp").textContent=state.xp;$("#streak").textContent=state.streak}
function renderHome(){renderCommon();const done=state.completed.filter(lessonById).length,p=Math.round(done/LESSONS.length*100),next=nextLesson();$("#progressPercent").textContent=p+"%";$("#progressRing").style.setProperty("--p",p);$("#homeXp").textContent=state.xp;$("#homeStreak").textContent=`${state.streak} Tag${state.streak===1?"":"e"}`;$("#homeLessons").textContent=done;$("#continueTitle").textContent=next?next.title:"Alles geschafft";$("#continueMeta").textContent=next?`${next.level} · ${next.chapterTitle}`:"Wiederhole schwierige Inhalte";const ex=Math.min(20,state.daily.exercises),goal=Math.round((ex/20)*100);$("#dailyGoalLabel").textContent=`${ex} / 20 Übungen`;$("#dailyGoalBar").style.width=goal+"%";$("#goalExercises").textContent=state.daily.exercises>=20?"✓":"○";$("#goalReview").textContent=state.daily.reviews>=5?"✓":"○";$("#goalDialogue").textContent=state.daily.dialogues>=1?"✓":"○"}
function renderLevels(){renderCommon();const host=$("#levelCards");host.innerHTML="";DATA.levels.forEach(level=>{const locked=!level.chapters.length,pr=levelProgress(level.id),b=document.createElement("button");b.className="levelSelect"+(locked?" locked":"");b.innerHTML=`<span class="levelBadge">${level.id}</span><div><h2>${level.title}</h2><p>${locked?"In Vorbereitung":`${level.chapters.length} Kapitel · ${pr.total} Lektionen`}</p>${locked?"":`<div class="miniProgress"><div style="width:${pr.p}%"></div></div>`}</div><strong>${locked?"🔒":pr.p+"%"}</strong>`;if(!locked)b.onclick=()=>openLevel(level.id);host.appendChild(b)});$("#levelCards").classList.remove("hidden");$("#levelDetail").classList.add("hidden")}
function openLevel(id){state.selectedLevel=id;save();$("#levelCards").classList.add("hidden");$("#levelDetail").classList.remove("hidden");renderCourse()}
function renderCourse(){const level=DATA.levels.find(x=>x.id===state.selectedLevel)||DATA.levels[0];$("#courseTitle").textContent=level.title;$("#courseDescription").textContent=`${level.chapters.length} Kapitel · ${levelLessons(level.id).length} Lektionen inklusive Kapiteltests`;$("#dueCount").textContent=due().length+" Wiederholungen fällig";const host=$("#chapters");host.innerHTML="";level.chapters.forEach((chapter,ci)=>{const all=LESSONS.filter(l=>l.chapterId===chapter.id),completed=all.filter(l=>state.completed.includes(l.id)).length,locked=!chapterUnlocked(chapter,ci),section=document.createElement("section");section.className="chapter"+(locked?" chapterLocked":"");section.innerHTML=`<div class="chapterHead"><div class="chapterIcon">${chapter.icon}</div><div><p class="eyebrow">Kapitel ${ci+1}</p><h2>${chapter.title}</h2><p>${chapter.description}</p></div><strong>${completed}/${all.length}</strong></div><div class="chapterProgress"><div style="width:${Math.round(completed/all.length*100)}%"></div></div><div class="lessonList"></div>`;const list=section.querySelector(".lessonList");all.forEach(l=>{const unlocked=lessonUnlocked(l,chapter,ci),done=state.completed.includes(l.id),stars=state.testStars[l.id]||0,row=document.createElement("article");row.className="unit"+(!unlocked?" locked":"")+(l.isTest?" testUnit":"");row.innerHTML=`<div class="lessonSymbol">${l.isTest?"✓":chapter.icon}</div><div><h3>${l.title}</h3><p>${l.description}</p>${l.isTest&&stars?`<div class="stars">${"★".repeat(stars)}${"☆".repeat(3-stars)}</div>`:""}</div><button ${unlocked?"":"disabled"}>${done?"Wiederholen":l.isTest?"Test starten":"Starten"}</button>`;row.querySelector("button").onclick=()=>startLesson(l.id);list.appendChild(row)});host.appendChild(section)})}
function wrongItems(){const rows=[];learningLessons().forEach(l=>l.items.forEach((it,i)=>{const k=itemKey(l.id,i),s=st(k);if(s.wrong>0)rows.push({...it,key:k,wrong:s.wrong,lessonId:l.id})}));return rows.sort((a,b)=>b.wrong-a.wrong)}
function renderPractice(){renderCommon();const d=due(),w=wrongItems();$("#practiceDueCount").textContent=d.length?`${d.length} Aufgaben bereit`:"Heute nichts fällig";$("#practiceWrongCount").textContent=w.length?`${w.length} schwierige Begriffe`:"Noch keine Fehler";const host=$("#wrongList");host.innerHTML=w.length?"":"<p>Noch keine schwierigen Begriffe. Das ist ein guter Anfang.</p>";w.slice(0,8).forEach(it=>{const div=document.createElement("div");div.className="wrongItem";div.innerHTML=`<div><b>${it.hr}</b><small>${it.de} · ${it.wrong} Fehler</small></div><span>›</span>`;host.appendChild(div)})}
function renderProfile(){renderCommon();const completeChapters=DATA.levels.flatMap(l=>l.chapters).filter(c=>state.completed.includes(c.testId)).length,minutes=Math.round((state.studySeconds||0)/60);$("#profileAccuracy").textContent=state.total?Math.round(state.correct/state.total*100)+"%":"–";$("#profileLearned").textContent=Object.values(state.items).filter(x=>x.seen>0).length;$("#profileChapters").textContent=completeChapters;$("#profileBestStreak").textContent=state.bestStreak||1;$("#profileTime").textContent=minutes+" Min.";$("#profileXp").textContent=state.xp;const host=$("#profileLevels");host.innerHTML="";DATA.levels.filter(l=>l.chapters.length).forEach(l=>{const p=levelProgress(l.id),div=document.createElement("div");div.className="profileLevel";div.innerHTML=`<div class="profileLevelHead"><b>${l.title}</b><span>${p.done}/${p.total}</span></div><div class="miniProgress"><div style="width:${p.p}%"></div></div>`;host.appendChild(div)})}
function achievementData(){const learned=Object.values(state.items).filter(x=>x.seen>0).length,chapters=DATA.levels.flatMap(l=>l.chapters).filter(c=>state.completed.includes(c.testId)).length;return [{icon:"👣",title:"Erster Korak",text:"Schließe deine erste Lektion ab",ok:state.completed.length>=1},{icon:"🔥",title:"7-Tage-Serie",text:"Lerne sieben Tage hintereinander",ok:state.bestStreak>=7},{icon:"📚",title:"100 Begriffe",text:"Trainiere 100 verschiedene Begriffe",ok:learned>=100},{icon:"⭐",title:"XP-Sammler",text:"Sammle 1.000 XP",ok:state.xp>=1000},{icon:"🏁",title:"Kapitel geschafft",text:"Bestehe deinen ersten Kapiteltest",ok:chapters>=1},{icon:"🌊",title:"A1 abgeschlossen",text:"Schließe den gesamten A1-Kurs ab",ok:levelProgress('A1').p===100},{icon:"🗣️",title:"Dialogstarter",text:"Trainiere deinen ersten Dialog",ok:(state.daily.dialogues||0)>0||Object.keys(state.items).some(k=>k.startsWith('dialog-'))},{icon:"🎯",title:"Treffsicher",text:"Erreiche mindestens 90 % Genauigkeit",ok:state.total>=20&&state.correct/state.total>=.9},{icon:"🏆",title:"Drei Sterne",text:"Erreiche drei Sterne in einem Kapiteltest",ok:Object.values(state.testStars).some(x=>x===3)}]}
function renderAchievements(){renderCommon();const host=$("#achievementGrid");host.innerHTML="";achievementData().forEach(a=>{const div=document.createElement("article");div.className="achievement"+(a.ok?"":" locked");div.innerHTML=`<span>${a.icon}</span><h3>${a.title}</h3><p>${a.text}</p>`;host.appendChild(div)})}
/* ---------- Übungstypen: Aufgaben werden pro Begriff zufällig aus einem Pool gezogen ---------- */
const HAS_TTS="speechSynthesis" in window,RECOG=["choice-de","listen-choice"],SPEAK_BEFORE=["choice-de","listen","listen-choice","dialogue"];
const KIND={"choice-de":"Kroatisch verstehen","choice-hr":"Ins Kroatische wählen","input-hr":"Ins Kroatische übersetzen",listen:"Hören und schreiben","listen-choice":"Hörverständnis",dialogue:"Dialog vervollständigen",match:"Paare verbinden",cloze:"Lücke füllen",order:"Satz bauen",odd:"Was passt nicht?"};
const PRAISE=["Richtig!","Super!","Odlično!","Bravo!","Točno!"];
// Themenfamilien, damit „Was passt nicht?“ keinen Begriff aus einem verwandten Kapitel als Ausreißer wählt.
const FAMILY={"a1-putovanje":"reise","a2-smjestaj":"reise","a2-promet":"reise","a1-hrana":"essen","a2-restoran":"essen","a1-kupovina":"geld","a2-novac":"geld","a1-svakodnevica":"alltag gesundheit wetter","a2-hitno":"gesundheit","a2-tijelo":"gesundheit","a2-vrijeme":"wetter","a2-posao":"arbeit","b1-karijera":"arbeit","a1-obitelj":"menschen arbeit","a1-begruessung":"menschen","a2-svakodnevica":"menschen","b1-misljenje":"menschen","a2-dom":"zuhause"};
const pick=a=>a[Math.floor(Math.random()*a.length)],strip=w=>w.replace(/[.!?,;:„“"…]/g,""),tokens=s=>String(s).split(/\s+/).map(strip).filter(Boolean),fam=id=>(FAMILY[id]||id).split(" ");
let WORDS=null;
function wordPool(){return WORDS||(WORDS=[...new Set(learningLessons().flatMap(l=>l.items.flatMap(x=>tokens(x.hr))).filter(w=>w.length>=4&&w===w.toLocaleLowerCase("hr")))])}
function clozeIndexes(it){return it.hr.split(/\s+/).map(strip).map((w,i)=>w.length>=4&&w===w.toLocaleLowerCase("hr")?i:-1).filter(i=>i>=0)}
function canCloze(it){return tokens(it.hr).length>=3&&clozeIndexes(it).length>0}
function canOrder(it){const n=tokens(it.hr).length;return n>=3&&n<=8}
function shuffleDifferent(w){let s=shuffle(w);for(let i=0;i<6&&s.join(" ")===w.join(" ");i++)s=shuffle(w);return s}
function ex(type,it){const base={type,key:it.key,item:it,spoken:it.hr,isReview:it.isReview};switch(type){
case "choice-de":return {...base,prompt:`Was bedeutet „${it.hr}“?`,answer:it.de,options:[it.de,...distract(it.de,"de")]};
case "choice-hr":return {...base,prompt:`Welche kroatische Antwort bedeutet „${it.de}“?`,answer:it.hr,options:[it.hr,...distract(it.hr,"hr")]};
case "listen":return {...base,prompt:"Tippe auf Anhören und schreibe den kroatischen Ausdruck.",answer:it.hr};
case "listen-choice":return {...base,prompt:"Hör genau hin: Was bedeutet das?",answer:it.de,options:[it.de,...distract(it.de,"de")]};
case "cloze":{const raw=it.hr.split(/\s+/),i=pick(clozeIndexes(it)),word=strip(raw[i]),gap=raw.map((x,k)=>k===i?x.replace(word,"_____"):x).join(" ");return {...base,prompt:`${gap}\n„${it.de}“`,answer:word,options:[word,...shuffle(wordPool().filter(x=>norm(x)!==norm(word))).slice(0,3)]}}
case "order":{const w=tokens(it.hr);return {...base,prompt:`Bilde den Satz: „${it.de}“`,answer:w.join(" "),words:shuffleDifferent(w)}}
default:return {...base,type:"input-hr",prompt:`Übersetze ins Kroatische: ${it.de}`,answer:it.hr}}}
function recogType(){return HAS_TTS&&Math.random()<.3?"listen-choice":"choice-de"}
function prodType(it){const t=["input-hr","input-hr","choice-hr"];if(HAS_TTS)t.push("listen");if(canOrder(it))t.push("order","order");if(canCloze(it))t.push("cloze","cloze");return pick(t)}
function pairFor(it){return [ex(recogType(),it),ex(prodType(it),it)]}
function matchEx(its){const uniq=its.filter((x,i,a)=>a.findIndex(y=>norm(y.de)===norm(x.de)||norm(y.hr)===norm(x.hr))===i),short=uniq.filter(x=>tokens(x.hr).length<=4),p=shuffle(short.length>=4?short:uniq).slice(0,4);return p.length>=3?{type:"match",prompt:"Verbinde jeden kroatischen Ausdruck mit seiner Bedeutung.",pairs:p,answer:""}:null}
function oddEx(its,chapterId,topic){const short=its.filter((x,i,a)=>tokens(x.hr).length<=2&&a.findIndex(y=>y.hr===x.hr)===i);if(short.length<3)return null;const same=shuffle(short).slice(0,3),f=fam(chapterId),others=learningLessons().filter(l=>!fam(l.chapterId).some(x=>f.includes(x))).flatMap(l=>l.items).filter(x=>tokens(x.hr).length<=2&&!same.some(y=>norm(y.hr)===norm(x.hr)));if(!others.length)return null;const odd=pick(others);return {type:"odd",prompt:`Welcher Ausdruck passt nicht zum Thema „${topic}“?`,answer:odd.hr,options:[odd.hr,...same.map(x=>x.hr)],info:[...same,odd]}}
function dialogueEx(l){if(!l.dialogue||l.dialogue.length<2)return null;const a=l.dialogue[0][1],b=l.dialogue[1][1];return {type:"dialogue",prompt:`Dialog ergänzen:\nA: ${a}\nB: …`,answer:b,options:[b,...distract(b,"hr")],spoken:a,key:`dialog-${l.id}`,item:{hr:b,de:"Passende Antwort im Dialog"}}}
// Wiedererkennen (Bedeutung wählen) soll vor dem aktiven Produzieren desselben Begriffs kommen.
function recogFirst(e){for(let i=0;i<e.length;i++){const q=e[i];if(!q.key||RECOG.includes(q.type))continue;const j=e.findIndex((x,k)=>k>i&&x.key===q.key&&RECOG.includes(x.type));if(j>i){e[i]=e[j];e[j]=q}}return e}
function lessonItems(l){return l.items.map((it,i)=>({...it,key:itemKey(l.id,i)}))}
function makeNormal(l){const its=lessonItems(l),e=its.flatMap(pairFor);shuffle(its).slice(0,2).forEach(it=>e.push(ex(prodType(it),it)));[matchEx(its),oddEx(its,l.chapterId,l.title),dialogueEx(l)].forEach(x=>x&&e.push(x));due().slice(0,3).forEach(it=>e.push(ex(recogType(),{...it,isReview:true})));return recogFirst(shuffle(e))}
function makeTest(l){const items=shuffle(chapterLessons(l.chapterId).flatMap(lessonItems)).slice(0,15),e=items.flatMap(pairFor);[matchEx(items),oddEx(items,l.chapterId,l.chapterTitle)].forEach(x=>x&&e.push(x));return recogFirst(shuffle(e))}
function startSession(q,m,l=null){active=l;mode=m;queue=q;pos=0;session={correct:0,total:0,dialogues:0,reviews:0,start:Date.now()};show("lesson");renderQ()}
function startLesson(id){const l=lessonById(id);if(!l||!isUnlocked(l))return;state.lastLesson=id;state.selectedLevel=l.level;save();startSession(l.isTest?makeTest(l):makeNormal(l),l.isTest?"test":"lesson",l)}
function startReview(){const d=due();if(!d.length)return alert("Heute ist noch keine Wiederholung fällig.");startSession(recogFirst(shuffle(d.flatMap(it=>pairFor({...it,isReview:true})))),"review")}
function startWrongPractice(){const w=wrongItems();if(!w.length)return alert("Noch keine häufig falsch beantworteten Fragen vorhanden.");const its=w.slice(0,20);startSession(recogFirst(shuffle([...its.flatMap(pairFor),matchEx(its)].filter(Boolean))),"wrong")}
function startRandom(){const unlocked=learningLessons().filter(isUnlocked),items=shuffle(unlocked.flatMap(lessonItems)).slice(0,10);if(!items.length)return;startSession(recogFirst(shuffle([...items.flatMap(pairFor),matchEx(items)].filter(Boolean))),"random")}
function showTests(){show("levels");openLevel(state.selectedLevel||"A1");setTimeout(()=>document.querySelector('.testUnit')?.scrollIntoView({behavior:'smooth'}),100)}
function renderQ(){if(pos>=queue.length)return finish();checked=false;answer="";const q=queue[pos];$("#counter").textContent=`${pos+1}/${queue.length}`;$("#bar").style.width=(pos/queue.length*100)+"%";$("#prompt").textContent=q.prompt;$("#kind").textContent=(q.isReview?"Wiederholung · ":"")+(KIND[q.type]||"");const tip=$("#grammarTip");tip.className="grammarTip"+(active&&active.grammar&&pos===0?"":" hidden");tip.textContent=active&&active.grammar?"💡 "+active.grammar:"";$("#feedback").className="feedback hidden";$("#check").classList.remove("hidden");$("#next").classList.add("hidden");$("#check").disabled=true;const card=$(".lessonCard");card.classList.remove("shake","celebrate");card.dataset.type=q.type;const sp=$("#speak");sp.classList.toggle("hidden",!HAS_TTS||!SPEAK_BEFORE.includes(q.type));sp.onclick=()=>speak(q.spoken);const a=$("#answerArea");a.innerHTML="";if(document.activeElement&&document.activeElement!==document.body&&!document.activeElement.closest(".dict"))document.activeElement.blur();if(q.type==="match")renderMatch(q,a);else if(q.type==="order")renderOrder(q,a);else if(q.options)renderChoices(q,a);else renderInput(q,a);if(q.type==="listen"||q.type==="listen-choice")setTimeout(()=>speak(q.spoken),300)}
function renderChoices(q,a){const list=document.createElement("div");list.className="choiceList"+(q.type==="odd"||q.type==="cloze"?" compact":"");shuffle(q.options).forEach((o,i)=>{const b=document.createElement("button");b.className="choice";b.dataset.value=o;b.innerHTML=`<kbd>${i+1}</kbd><span></span>`;b.lastChild.textContent=o;b.onclick=()=>{if(checked)return;answer=o;[...list.children].forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("#check").disabled=false};list.appendChild(b)});a.appendChild(list)}
function renderInput(q,a){const i=document.createElement("input");i.className="textInput";i.placeholder="Kroatische Antwort";i.autocomplete="off";i.autocapitalize="off";i.spellcheck=false;i.oninput=()=>{answer=i.value;$("#check").disabled=!norm(answer)};i.onkeydown=e=>{if(e.key!=="Enter")return;e.preventDefault();if(checked)goNext();else if(!$("#check").disabled)check()};const keys=document.createElement("div");keys.className="charKeys";["č","ć","đ","š","ž"].forEach(c=>{const b=document.createElement("button");b.type="button";b.textContent=c;b.onmousedown=e=>e.preventDefault();b.onclick=()=>{if(checked)return;const s=i.selectionStart??i.value.length,t=i.selectionEnd??s;i.value=i.value.slice(0,s)+c+i.value.slice(t);i.setSelectionRange(s+1,s+1);i.focus();i.oninput()};keys.appendChild(b)});a.append(i,keys);setTimeout(()=>i.focus(),50)}
function renderOrder(q,a){const line=document.createElement("div"),bank=document.createElement("div");line.className="orderLine";bank.className="wordBank";const sync=()=>{answer=[...line.children].map(x=>x.textContent).join(" ");$("#check").disabled=bank.children.length>0};q.words.forEach(w=>{const b=document.createElement("button");b.className="chip";b.textContent=w;b.onclick=()=>{if(checked)return;(b.parentNode===bank?line:bank).appendChild(b);sync()};bank.appendChild(b)});a.append(line,bank)}
function renderMatch(q,a){q.wrong=new Set();q.misses=0;let sel=null,done=0;const grid=document.createElement("div");grid.className="matchGrid";const cols={hr:document.createElement("div"),de:document.createElement("div")};Object.values(cols).forEach(c=>{c.className="matchCol";grid.appendChild(c)});["hr","de"].forEach(side=>shuffle(q.pairs.map((p,i)=>i)).forEach(i=>{const b=document.createElement("button");b.className="choice matchItem";b.textContent=q.pairs[i][side];b.onclick=()=>{if(checked||b.disabled)return;if(!sel||sel.side===side){if(sel)sel.b.classList.remove("selected");sel={side,i,b};b.classList.add("selected");if(side==="hr")speak(q.pairs[i].hr);return}const other=sel;sel=null;other.b.classList.remove("selected");if(other.i===i){[other.b,b].forEach(x=>{x.classList.add("matched");x.disabled=true});if(++done===q.pairs.length){answer="ok";$("#check").disabled=false;setTimeout(check,350)}}else{q.misses++;q.wrong.add(i);q.wrong.add(other.i);[other.b,b].forEach(x=>{x.classList.add("mismatch");setTimeout(()=>x.classList.remove("mismatch"),550)})}};cols[side].appendChild(b)}));a.appendChild(grid)}
function speak(t){if(!HAS_TTS||!t)return;const u=new SpeechSynthesisUtterance(t);u.lang="hr-HR";u.rate=.78;const v=speechSynthesis.getVoices().find(x=>x.lang.toLowerCase().startsWith("hr"));if(v)u.voice=v;speechSynthesis.cancel();speechSynthesis.speak(u)}
function retryFor(q){if(q.type==="odd")return null;if(q.type==="match"||q.type==="dialogue")return {...q};if(!q.item)return null;return ex(RECOG.includes(q.type)?"input-hr":"choice-hr",q.item)}
function check(){if(checked)return;checked=true;const q=queue[pos],fb=$("#feedback");let ok,near=false;if(q.type==="match")ok=q.wrong.size===0;else{ok=norm(answer)===norm(q.answer);if(!ok&&(q.type==="input-hr"||q.type==="listen")&&plain(answer)===plain(q.answer))ok=near=true}state.total++;session.total++;state.daily.exercises++;if(ok){state.correct++;session.correct++;state.xp+=8;fb.textContent=near?`Fast perfekt – achte auf die Sonderzeichen: ${q.answer} (+8 XP)`:`${pick(PRAISE)} +8 XP`}else{fb.textContent=q.type==="match"?`Geschafft – ${q.misses>1?q.misses+" Fehlversuche":"ein Fehlversuch"}. Die Paare kommen gleich noch einmal.`:`Richtig wäre: ${q.type==="cloze"?q.answer+" – "+q.item.hr:q.type==="order"?q.item.hr:q.answer}`;const r=retryFor(q);if(r)queue.splice(Math.min(queue.length,pos+3),0,r)}if(q.type==="odd")fb.textContent+="\n"+q.info.map(x=>`${x.hr} = ${x.de}`).join("\n");fb.className="feedback "+(ok?"ok":"no");$(".lessonCard").classList.add(ok?"celebrate":"shake");document.querySelectorAll("#answerArea .choice:not(.matchItem)").forEach(b=>{if(norm(b.dataset.value)===norm(q.answer))b.classList.add("correct");else if(b.classList.contains("selected"))b.classList.add("wrong")});const inp=$("#answerArea .textInput");if(inp){inp.readOnly=true;inp.classList.add(ok?"correct":"wrong")}const line=$("#answerArea .orderLine");if(line)line.classList.add(ok?"correct":"wrong");if(q.type==="dialogue"){state.daily.dialogues++;session.dialogues++}if(q.isReview||mode==="review"){state.daily.reviews++;session.reviews++}if(q.type==="match")q.pairs.forEach((p,i)=>p.key&&schedule(p.key,!q.wrong.has(i)));else if(q.key)schedule(q.key,ok);updateStreak();save();renderCommon();if(q.item&&HAS_TTS&&q.type!=="dialogue"){const sp=$("#speak");sp.classList.remove("hidden");sp.onclick=()=>speak(q.item.hr)}$("#check").classList.add("hidden");$("#next").classList.remove("hidden")}
function goNext(){if(!checked)return;pos++;renderQ()}
function finish(){state.studySeconds=(state.studySeconds||0)+Math.max(0,Math.round((Date.now()-session.start)/1000));let stars=0;if(active){if(!state.completed.includes(active.id)){state.completed.push(active.id);state.xp+=active.isTest?60:30}if(active.isTest){const rate=session.total?session.correct/session.total:0;stars=rate>=.9?3:rate>=.75?2:1;state.testStars[active.id]=Math.max(state.testStars[active.id]||0,stars)}}save();const pct=session.total?Math.round(session.correct/session.total*100):100;$("#doneText").textContent=mode==="review"?"Deine fälligen Wiederholungen sind erledigt.":active&&active.isTest?"Kapiteltest abgeschlossen. Das nächste Kapitel ist jetzt freigeschaltet.":"Du hast Wortschatz, Hörverständnis und praktische Situationen trainiert.";$("#doneScore").innerHTML=active&&active.isTest?`<div class="scoreStars">${"★".repeat(stars)}${"☆".repeat(3-stars)}</div><p>${pct}% richtig</p>`:`<p>${session.correct} von ${session.total} direkt richtig</p>`;show("done")}
document.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>show(b.dataset.screen));$("#continueBtn").onclick=()=>startLesson((nextLesson()||{}).id);$("#levelBack").onclick=renderLevels;$("#reviewBtn").onclick=startReview;$("#practiceDue").onclick=startReview;$("#practiceWrong").onclick=startWrongPractice;$("#practiceRandom").onclick=startRandom;$("#practiceTests").onclick=showTests;$("#check").onclick=check;$("#next").onclick=goNext;addEventListener("keydown",e=>{if(!$("#lesson").classList.contains("active")||e.target.closest(".dict")||e.target.tagName==="INPUT")return;if(e.key==="Enter"){e.preventDefault();if(checked)goNext();else if(!$("#check").disabled)check()}else if(/^[1-5]$/.test(e.key)&&!checked){const b=document.querySelectorAll("#answerArea .choice:not(.matchItem)")[e.key-1];if(b)b.click()}});$("#close").onclick=()=>show(active?"levels":"practice");$("#homeBtn").onclick=()=>show("home");resetDaily();show("home");if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
