const DATA=window.KORAK_DATA,LESSONS=DATA.lessons,KEY="korak-v6",OLD_KEYS=["korak-v5","korak-a1-v3"],DAY=86400000,INTERVALS=[0,1,3,7,14,30,60,90];
let state=load(),active=null,queue=[],pos=0,answer="",checked=false,mode="lesson",session={correct:0,total:0,dialogues:0,reviews:0,start:0};
const $=s=>document.querySelector(s),lessonById=id=>LESSONS.find(l=>l.id===id),levelLessons=id=>LESSONS.filter(l=>l.level===id),chapterLessons=id=>LESSONS.filter(l=>l.chapterId===id&&!l.isTest);
function defaults(){return {xp:0,streak:1,bestStreak:1,completed:[],items:{},lastStudy:null,lastLesson:"a1-1-1",selectedLevel:"A1",total:0,correct:0,testStars:{},studySeconds:0,daily:{date:"",exercises:0,reviews:0,dialogues:0}}}
function load(){try{let cur=JSON.parse(localStorage.getItem(KEY)||"null");if(cur)return Object.assign(defaults(),cur);for(const k of OLD_KEYS){const old=JSON.parse(localStorage.getItem(k)||"null");if(old){const s=Object.assign(defaults(),old);if(k==="korak-a1-v3")s.completed=(old.completed||[]).map(n=>`a1-${Math.floor((n-1)/5)+1}-${((n-1)%5)+1}`).filter(lessonById);localStorage.setItem(KEY,JSON.stringify(s));return s}}}catch(e){}return defaults()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function resetDaily(){if(state.daily.date!==today())state.daily={date:today(),exercises:0,reviews:0,dialogues:0}}
function updateStreak(){const t=today();if(state.lastStudy===t)return;const y=new Date(Date.now()-DAY).toISOString().slice(0,10);state.streak=state.lastStudy===y?(state.streak||1)+1:1;state.bestStreak=Math.max(state.bestStreak||1,state.streak);state.lastStudy=t}
function norm(s){return String(s||"").trim().toLocaleLowerCase("hr").replace(/[.!?,;:„“"'…–—()]/g,"").replace(/\s+/g," ")}
function plain(s){return norm(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/dj|đ/g,"d")}
function itemKey(lid,i){return `${lid}-${i}`}
function st(k){return state.items[k]||{box:0,due:0,seen:0,correct:0,wrong:0}}
function schedule(k,ok){const s=st(k);s.seen++;if(ok){s.correct++;s.box=Math.min(INTERVALS.length-1,s.box+1)}else{s.wrong++;s.box=Math.max(0,s.box-2)}s.due=Date.now()+INTERVALS[s.box]*DAY;state.items[k]=s}
function learningLessons(){return LESSONS.filter(l=>!l.isTest)}
function due(){const out=[];learningLessons().forEach(l=>l.items.forEach((it,i)=>{const k=itemKey(l.id,i),s=st(k);if(s.seen&&s.due<=Date.now())out.push({...it,key:k,lessonId:l.id})}));return out}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function pool(field){return [...new Set(learningLessons().flatMap(l=>l.items.map(x=>x[field])))]}
function distract(cur,field){return shuffle(pool(field).filter(x=>x!==cur)).slice(0,3)}
function chapterUnlocked(chapter,index){if(index===0)return true;const lev=DATA.levels.find(x=>x.id===chapter.level),prev=lev.chapters[index-1];return state.completed.includes(prev.testId)}
function lessonUnlocked(lesson,chapter,index){if(!chapterUnlocked(chapter,index))return false;const all=LESSONS.filter(l=>l.chapterId===chapter.id),idx=all.findIndex(x=>x.id===lesson.id);return idx===0||state.completed.includes(all[idx-1].id)}
function isUnlocked(l){const lev=DATA.levels.find(x=>x.id===l.level),ci=lev.chapters.findIndex(c=>c.id===l.chapterId);return lessonUnlocked(l,lev.chapters[ci],ci)}
function nextLesson(){const list=levelLessons(state.selectedLevel||"A1");return list.find(l=>!state.completed.includes(l.id)&&isUnlocked(l))||list.find(isUnlocked)||list[0]}
function levelProgress(id){const list=levelLessons(id),done=list.filter(l=>state.completed.includes(l.id)).length;return {done,total:list.length,p:list.length?Math.round(done/list.length*100):0}}
/* ---------- Oberfläche: Icons, Navigation, Hinweise ---------- */
const VIEWS=["home","levels","practice","profile","achievements","lesson","done"];
const CHAPTER_ICON={"a1-begruessung":"chat","a1-obitelj":"people","a1-hrana":"bowl","a1-kupovina":"bag","a1-putovanje":"map","a1-svakodnevica":"sun","a2-proslost":"history","a2-buducnost":"calendar","a2-smjestaj":"bed","a2-restoran":"glass","a2-svakodnevica":"phone","a2-posao":"briefcase","a2-hitno":"cross","a2-promet":"train","a2-dom":"sofa","a2-vrijeme":"cloud","a2-novac":"euro","a2-tijelo":"heart","b1-misljenje":"chat2","b1-karijera":"trend","b1-drustvo":"news"};
const icon=(n,cls="")=>`<svg class="ico ${cls}" aria-hidden="true"><use href="#i-${n}"/></svg>`;
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const plural=(n,one,many)=>`${n} ${n===1?one:many}`;
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),2800)}
function moveDock(){const b=document.querySelector(".dock button.active"),pill=$(".dockPill");if(!b){pill.style.opacity=0;return}pill.style.opacity=1;pill.style.setProperty("--x",b.offsetLeft+"px");pill.style.setProperty("--w",b.offsetWidth+"px")}
function greeting(){const h=new Date().getHours();return h<10?"Dobro jutro":h<18?"Dobar dan":"Dobra večer"}
function countUp(el,to,ms=900){const start=performance.now();const tick=t=>{const k=Math.min(1,(t-start)/ms),e=1-Math.pow(1-k,4);el.textContent=Math.round(to*e);if(k<1)requestAnimationFrame(tick)};matchMedia("(prefers-reduced-motion: reduce)").matches?el.textContent=to:requestAnimationFrame(tick)}
function show(id){document.body.classList.toggle("inLesson",id==="lesson");VIEWS.forEach(v=>$("#"+v).classList.toggle("active",v===id));document.querySelectorAll(".dock [data-screen]").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));moveDock();if(id==="home")renderHome();if(id==="levels")renderLevels();if(id==="practice")renderPractice();if(id==="profile")renderProfile();if(id==="achievements")renderAchievements();[...$("#"+id).children].forEach((c,i)=>c.style.setProperty("--i",i));scrollTo(0,0)}
function renderCommon(){resetDaily();[["#xp",state.xp],["#streak",state.streak]].forEach(([s,v])=>{const el=$(s),old=el.textContent;el.textContent=v;if(old!==String(v)&&old!==""){el.classList.remove("bump");void el.offsetWidth;el.classList.add("bump")}})}
function accuracy(){return state.total?Math.round(state.correct/state.total*100):null}
function renderHome(){renderCommon();const done=state.completed.filter(lessonById).length,total=LESSONS.length,next=nextLesson(),share=done/total*10;$("#greeting").textContent=greeting();$("#homeLessons").textContent=done;$("#homeTotal").textContent=total;$("#steps").innerHTML=Array.from({length:10},(_,i)=>{const f=Math.max(0,Math.min(1,share-i));return `<span class="${f>=1?"on":f>0?"part":""}" style="--h:${20+i*8.8};--n:${i};--f:${Math.round(f*100)}"></span>`}).join("");$("#continueTitle").textContent=next?next.title:"Alles geschafft";$("#continueMeta").textContent=next?`${next.chapterTitle}, Level ${next.level}`:"Wiederhole jetzt, was dir schwerfällt.";$("#continueBtn span").textContent=done?"Weiterlernen":"Erste Lektion starten";const ex=Math.min(20,state.daily.exercises);$("#dailyGoalLabel").textContent=`${ex} von 20 Übungen`;$("#dailyGoalBar").style.width=ex/20*100+"%";$("#goalExercises").classList.toggle("met",state.daily.exercises>=20);$("#goalReview").classList.toggle("met",state.daily.reviews>=5);$("#goalDialogue").classList.toggle("met",state.daily.dialogues>=1);$("#homeStreak").textContent=plural(state.streak,"Tag","Tage");$("#homeXp").textContent=state.xp;const acc=accuracy();$("#homeAccuracy").textContent=acc===null?"–":acc+" %"}
function renderLevels(){renderCommon();const host=$("#levelCards");host.innerHTML="";DATA.levels.forEach(level=>{const locked=!level.chapters.length,pr=levelProgress(level.id),b=document.createElement("button");b.className="levelRow"+(locked?" locked":"");b.disabled=locked;b.innerHTML=`<span class="levelCode">${esc(level.id)}</span><span><strong class="lrTitle">${esc(level.subtitle||level.title)}</strong><span class="lrMeta">${locked?"In Vorbereitung":`${level.chapters.length} Kapitel, ${pr.total} Lektionen`}</span>${locked?"":`<span class="track"><span style="width:${pr.p}%"></span></span>`}</span><span class="levelPct">${locked?icon("lock"):pr.p+" %"}</span>`;if(!locked)b.onclick=()=>openLevel(level.id);host.appendChild(b)});$("#levelCards").classList.remove("hidden");$("#levelDetail").classList.add("hidden");$("#levels").classList.remove("detailOpen")}
function openLevel(id){state.selectedLevel=id;save();$("#levels").classList.add("detailOpen");$("#levelCards").classList.add("hidden");$("#levelDetail").classList.remove("hidden");renderCourse()}
function renderCourse(){const level=DATA.levels.find(x=>x.id===state.selectedLevel)||DATA.levels[0],cur=nextLesson(),d=due().length;$("#courseTitle").textContent=level.title;$("#courseDescription").textContent=`${level.chapters.length} Kapitel mit ${levelLessons(level.id).length} Lektionen und Tests`;$("#dueCount").textContent=d?`${plural(d,"Wiederholung","Wiederholungen")} fällig`:"Keine Wiederholungen fällig";const host=$("#chapters");host.innerHTML="";level.chapters.forEach((chapter,ci)=>{const all=LESSONS.filter(l=>l.chapterId===chapter.id),completed=all.filter(l=>state.completed.includes(l.id)).length,locked=!chapterUnlocked(chapter,ci),sec=document.createElement("section");sec.className="chapter"+(locked?" chapterLocked":"");sec.innerHTML=`<div class="chapterHead"><div class="chapterIcon">${icon(locked?"lock":CHAPTER_ICON[chapter.id]||"stairs")}</div><div><span class="chapterNo">Kapitel ${ci+1}</span><h2>${esc(chapter.title)}</h2><p>${esc(chapter.description)}</p></div><span class="chapterCount">${completed}/${all.length}</span></div><div class="path"><svg class="pathLine" aria-hidden="true"></svg></div>`;const path=sec.querySelector(".path");all.forEach((l,i)=>{const unlocked=lessonUnlocked(l,chapter,ci),done=state.completed.includes(l.id),isCur=!done&&unlocked&&cur&&cur.id===l.id,stars=state.testStars[l.id]||0,b=document.createElement("button");b.className="stone"+(l.isTest?" test":"")+(done?" done":"")+(isCur?" current":"")+(unlocked?"":" locked");b.disabled=!unlocked;b.style.setProperty("--x",`calc(var(--swing) * ${Math.sin(i*1.2).toFixed(3)})`);const sym=!unlocked?"lock":done?(l.isTest?"star":"check"):isCur?"play":l.isTest?"star":CHAPTER_ICON[chapter.id]||"stairs";b.innerHTML=`<span class="node">${icon(sym)}</span><span class="stoneLabel"><b>${esc(l.isTest?"Kapiteltest":l.title)}</b><small>${esc(l.isTest?"Schaltet das nächste Kapitel frei":done?"Erledigt, jederzeit wiederholbar":l.description)}</small>${l.isTest&&stars?`<span class="stars" aria-label="${stars} von 3 Sternen">${[0,1,2].map(k=>icon("star",k<stars?"on":"")).join("")}</span>`:""}</span>`;b.onclick=()=>startLesson(l.id);path.appendChild(b)});host.appendChild(sec)});requestAnimationFrame(()=>drawPaths(true))}
// Verbindet die Trittsteine eines Kapitels mit einer geschwungenen Linie; der erledigte Teil ist durchgezogen.
function drawPaths(animate){document.querySelectorAll("#chapters .path").forEach(path=>{const svg=path.querySelector(".pathLine"),stones=[...path.querySelectorAll(".stone")];if(!stones.length||!path.offsetWidth)return;const pts=stones.map(s=>{const n=s.querySelector(".node"),tx=new DOMMatrixReadOnly(getComputedStyle(s).transform).m41;return [s.offsetLeft+n.offsetLeft+n.offsetWidth/2+tx,s.offsetTop+n.offsetTop+n.offsetHeight/2]});const curve=p=>p.map((q,i)=>{if(!i)return `M${q[0]} ${q[1]}`;const o=p[i-1],dy=(q[1]-o[1])/2;return `C${o[0]} ${o[1]+dy} ${q[0]} ${q[1]-dy} ${q[0]} ${q[1]}`}).join(" ");const doneN=stones.filter(s=>s.classList.contains("done")).length,reach=Math.min(doneN,pts.length-1);svg.setAttribute("viewBox",`0 0 ${path.offsetWidth} ${path.offsetHeight}`);svg.innerHTML=`<path d="${curve(pts)}"/>${reach>0?`<path class="progress" d="${curve(pts.slice(0,reach+1))}"/>`:""}`;const prog=svg.querySelector(".progress");svg.classList.remove("draw");if(prog&&animate){svg.style.setProperty("--len",Math.ceil(prog.getTotalLength()));void svg.getBoundingClientRect();svg.classList.add("draw")}})}
function wrongItems(){const rows=[];learningLessons().forEach(l=>l.items.forEach((it,i)=>{const k=itemKey(l.id,i),s=st(k);if(s.wrong>0)rows.push({...it,key:k,wrong:s.wrong,lessonId:l.id})}));return rows.sort((a,b)=>b.wrong-a.wrong)}
function renderPractice(){renderCommon();const d=due(),w=wrongItems();$("#practiceDueCount").textContent=d.length?`${plural(d.length,"Aufgabe","Aufgaben")} bereit`:"Heute ist nichts fällig";$("#practiceWrongCount").textContent=w.length?`${plural(w.length,"Begriff","Begriffe")} zum Festigen`:"Noch keine Fehler";const host=$("#wrongList");host.innerHTML=w.length?"":`<p class="empty"><b>Noch nichts Schwieriges.</b>Begriffe, die du falsch beantwortest, landen hier – mit Priorität fürs Üben.</p>`;w.slice(0,8).forEach(it=>{const div=document.createElement("div");div.innerHTML=`<span><b lang="hr">${esc(it.hr)}</b><small>${esc(it.de)}</small></span><span class="misses">${plural(it.wrong,"Fehler","Fehler")}</span>`;host.appendChild(div)})}
function renderProfile(){renderCommon();const completeChapters=DATA.levels.flatMap(l=>l.chapters).filter(c=>state.completed.includes(c.testId)).length,minutes=Math.round((state.studySeconds||0)/60),acc=accuracy();$("#profileAccuracy").textContent=acc===null?"–":acc+" %";$("#profileAnswers").textContent=state.total?`${state.correct} von ${state.total} Antworten richtig`:"Noch keine Antworten";$("#profileLearned").textContent=Object.values(state.items).filter(x=>x.seen>0).length;$("#profileChapters").textContent=completeChapters;$("#profileBestStreak").textContent=plural(state.bestStreak||1,"Tag","Tage");$("#profileTime").textContent=minutes+" Min.";$("#profileXp").textContent=state.xp;const host=$("#profileLevels");host.innerHTML="";DATA.levels.filter(l=>l.chapters.length).forEach(l=>{const p=levelProgress(l.id),div=document.createElement("div");div.className="levelProgress";div.innerHTML=`<div class="lpHead"><b>${esc(l.title)}</b><span>${p.done} von ${p.total}</span></div><div class="track"><div style="width:${p.p}%"></div></div>`;host.appendChild(div)})}
function achievementData(){const learned=Object.values(state.items).filter(x=>x.seen>0).length,chapters=DATA.levels.flatMap(l=>l.chapters).filter(c=>state.completed.includes(c.testId)).length;return [{icon:"stairs",title:"Erster Korak",text:"Schließe deine erste Lektion ab",ok:state.completed.length>=1},{icon:"flame",title:"Sieben Tage am Stück",text:"Lerne sieben Tage hintereinander",ok:state.bestStreak>=7},{icon:"book",title:"100 Begriffe",text:"Trainiere 100 verschiedene Begriffe",ok:learned>=100},{icon:"spark",title:"Tausend Punkte",text:"Sammle 1.000 Erfahrungspunkte",ok:state.xp>=1000},{icon:"flag",title:"Kapitel geschafft",text:"Bestehe deinen ersten Kapiteltest",ok:chapters>=1},{icon:"wave",title:"A1 abgeschlossen",text:"Schließe den gesamten A1-Kurs ab",ok:levelProgress('A1').p===100},{icon:"chat",title:"Erster Dialog",text:"Vervollständige deinen ersten Dialog",ok:(state.daily.dialogues||0)>0||Object.keys(state.items).some(k=>k.startsWith('dialog-'))},{icon:"target",title:"Treffsicher",text:"Erreiche mindestens 90 % Genauigkeit",ok:state.total>=20&&state.correct/state.total>=.9},{icon:"star",title:"Drei Sterne",text:"Erreiche drei Sterne in einem Kapiteltest",ok:Object.values(state.testStars).some(x=>x===3)}]}
function renderAchievements(){renderCommon();const list=achievementData(),host=$("#achievementGrid");$("#achieveCount").innerHTML=`<b>${list.filter(a=>a.ok).length}</b> von ${list.length} freigeschaltet`;host.innerHTML="";list.forEach(a=>{const div=document.createElement("article");div.className="achievement"+(a.ok?" earned":"");div.innerHTML=`<span class="badge">${icon(a.icon)}</span><div><h3>${esc(a.title)}</h3><p>${esc(a.text)}</p></div>`;host.appendChild(div)})}
/* ---------- Übungstypen: Aufgaben werden pro Begriff zufällig aus einem Pool gezogen ---------- */
const HAS_TTS="speechSynthesis" in window,RECOG=["choice-de","listen-choice"],SPEAK_BEFORE=["choice-de","listen","listen-choice","dialogue"];
const KIND={"choice-de":"Kroatisch verstehen","choice-hr":"Ins Kroatische wählen","input-hr":"Ins Kroatische übersetzen",listen:"Hören und schreiben","listen-choice":"Hörverständnis",dialogue:"Dialog vervollständigen",match:"Paare verbinden",cloze:"Lücke füllen",order:"Satz bauen",odd:"Was passt nicht?"};
const PRAISE=["Richtig!","Super!","Odlično!","Bravo!","Točno!"];
// Themenfamilien, damit „Was passt nicht?“ keinen Begriff aus einem verwandten Kapitel als Ausreißer wählt.
const FAMILY={"a1-putovanje":"reise","a2-smjestaj":"reise","a2-promet":"reise","a1-hrana":"essen","a2-restoran":"essen","a1-kupovina":"geld","a2-novac":"geld","a1-svakodnevica":"alltag gesundheit wetter","a2-hitno":"gesundheit","a2-tijelo":"gesundheit","a2-vrijeme":"wetter","a2-posao":"arbeit","b1-karijera":"arbeit","a1-obitelj":"menschen arbeit","a1-begruessung":"menschen","a2-svakodnevica":"menschen","b1-misljenje":"menschen","a2-dom":"zuhause"};
const pick=a=>a[Math.floor(Math.random()*a.length)],strip=w=>w.replace(/[.!?,;:„“"…]/g,""),tokens=s=>String(s).split(/\s+/).map(strip).filter(Boolean),fam=id=>(FAMILY[id]||id).split(" ");
let WORDS=null;
function wordPool(){return WORDS||(WORDS=[...new Set(learningLessons().flatMap(l=>l.items.flatMap(x=>tokens(x.hr))).filter(w=>w.length>=4&&w===w.toLocaleLowerCase("hr")))])}
function clozeIndexes(it){return it.hr.split(/\s+/).map(strip).map((w,i)=>w.length>=4&&w===w.toLocaleLowerCase("hr")?i:-1).filter(i=>i>=0)}
function canCloze(it){return tokens(it.hr).length>=3&&clozeIndexes(it).length>0}
function canOrder(it){const n=tokens(it.hr).length;return n>=3&&n<=8}
function shuffleDifferent(w){let s=shuffle(w);for(let i=0;i<6&&s.join(" ")===w.join(" ");i++)s=shuffle(w);return s}
function ex(type,it){const base={type,key:it.key,item:it,spoken:it.hr,isReview:it.isReview};switch(type){
case "choice-de":return {...base,prompt:`Was bedeutet „${it.hr}“?`,answer:it.de,options:[it.de,...distract(it.de,"de")]};
case "choice-hr":return {...base,prompt:`Welche kroatische Antwort bedeutet „${it.de}“?`,answer:it.hr,options:[it.hr,...distract(it.hr,"hr")]};
case "listen":return {...base,prompt:"Tippe auf Anhören und schreibe den kroatischen Ausdruck.",answer:it.hr};
case "listen-choice":return {...base,prompt:"Hör genau hin: Was bedeutet das?",answer:it.de,options:[it.de,...distract(it.de,"de")]};
case "cloze":{const raw=it.hr.split(/\s+/),i=pick(clozeIndexes(it)),word=strip(raw[i]),gap=raw.map((x,k)=>k===i?x.replace(word,"_____"):x).join(" ");return {...base,prompt:gap,hint:`„${it.de}“`,answer:word,options:[word,...shuffle(wordPool().filter(x=>norm(x)!==norm(word))).slice(0,3)]}}
case "order":{const w=tokens(it.hr);return {...base,prompt:`Bilde den Satz: „${it.de}“`,answer:w.join(" "),words:shuffleDifferent(w)}}
default:return {...base,type:"input-hr",prompt:`Übersetze ins Kroatische: ${it.de}`,answer:it.hr}}}
function recogType(){return HAS_TTS&&Math.random()<.3?"listen-choice":"choice-de"}
function prodType(it){const t=["input-hr","input-hr","choice-hr"];if(HAS_TTS)t.push("listen");if(canOrder(it))t.push("order","order");if(canCloze(it))t.push("cloze","cloze");return pick(t)}
function pairFor(it){return [ex(recogType(),it),ex(prodType(it),it)]}
function matchEx(its){const uniq=its.filter((x,i,a)=>a.findIndex(y=>norm(y.de)===norm(x.de)||norm(y.hr)===norm(x.hr))===i),short=uniq.filter(x=>tokens(x.hr).length<=4),p=shuffle(short.length>=4?short:uniq).slice(0,4);return p.length>=3?{type:"match",prompt:"Verbinde jeden kroatischen Ausdruck mit seiner Bedeutung.",pairs:p,answer:""}:null}
function oddEx(its,chapterId,topic){const short=its.filter((x,i,a)=>tokens(x.hr).length<=2&&a.findIndex(y=>y.hr===x.hr)===i);if(short.length<3)return null;const same=shuffle(short).slice(0,3),f=fam(chapterId),others=learningLessons().filter(l=>!fam(l.chapterId).some(x=>f.includes(x))).flatMap(l=>l.items).filter(x=>tokens(x.hr).length<=2&&!same.some(y=>norm(y.hr)===norm(x.hr)));if(!others.length)return null;const odd=pick(others);return {type:"odd",prompt:`Welcher Ausdruck passt nicht zum Thema „${topic}“?`,answer:odd.hr,options:[odd.hr,...same.map(x=>x.hr)],info:[...same,odd]}}
function dialogueEx(l){if(!l.dialogue||l.dialogue.length<2)return null;const a=l.dialogue[0][1],b=l.dialogue[1][1];return {type:"dialogue",prompt:`Dialog ergänzen:\nA: ${a}\nB: …`,answer:b,options:[b,...distract(b,"hr")],spoken:a,key:`dialog-${l.id}`,item:{hr:b,de:"Passende Antwort im Dialog"}}}
// Wiedererkennen (Bedeutung wählen) soll vor dem aktiven Produzieren desselben Begriffs kommen.
function recogFirst(e){for(let i=0;i<e.length;i++){const q=e[i];if(!q.key||RECOG.includes(q.type))continue;const j=e.findIndex((x,k)=>k>i&&x.key===q.key&&RECOG.includes(x.type));if(j>i){e[i]=e[j];e[j]=q}}return e}
function lessonItems(l){return l.items.map((it,i)=>({...it,key:itemKey(l.id,i)}))}
function makeNormal(l){const its=lessonItems(l),e=its.flatMap(pairFor);shuffle(its).slice(0,2).forEach(it=>e.push(ex(prodType(it),it)));[matchEx(its),oddEx(its,l.chapterId,l.title),dialogueEx(l)].forEach(x=>x&&e.push(x));due().slice(0,3).forEach(it=>e.push(ex(recogType(),{...it,isReview:true})));return recogFirst(shuffle(e))}
function makeTest(l){const items=shuffle(chapterLessons(l.chapterId).flatMap(lessonItems)).slice(0,15),e=items.flatMap(pairFor);[matchEx(items),oddEx(items,l.chapterId,l.chapterTitle)].forEach(x=>x&&e.push(x));return recogFirst(shuffle(e))}
function startSession(q,m,l=null){active=l;mode=m;queue=q;pos=0;session={correct:0,total:0,dialogues:0,reviews:0,start:Date.now()};show("lesson");renderQ()}
function startLesson(id){const l=lessonById(id);if(!l||!isUnlocked(l))return;state.lastLesson=id;state.selectedLevel=l.level;save();startSession(l.isTest?makeTest(l):makeNormal(l),l.isTest?"test":"lesson",l)}
function startReview(){const d=due();if(!d.length)return toast("Heute ist noch keine Wiederholung fällig.");startSession(recogFirst(shuffle(d.flatMap(it=>pairFor({...it,isReview:true})))),"review")}
function startWrongPractice(){const w=wrongItems();if(!w.length)return toast("Noch keine Fehler gesammelt – das ist ein gutes Zeichen.");const its=w.slice(0,20);startSession(recogFirst(shuffle([...its.flatMap(pairFor),matchEx(its)].filter(Boolean))),"wrong")}
function startRandom(){const unlocked=learningLessons().filter(isUnlocked),items=shuffle(unlocked.flatMap(lessonItems)).slice(0,10);if(!items.length)return;startSession(recogFirst(shuffle([...items.flatMap(pairFor),matchEx(items)].filter(Boolean))),"random")}
function showTests(){show("levels");openLevel(state.selectedLevel||"A1");setTimeout(()=>document.querySelector('.testUnit')?.scrollIntoView({behavior:'smooth'}),100)}
function renderQ(){if(pos>=queue.length)return finish();checked=false;answer="";const q=queue[pos];$("#counter").textContent=`${pos+1}/${queue.length}`;$("#bar").style.width=(pos/queue.length*100)+"%";$("#prompt").textContent=q.prompt;$("#promptHint").textContent=q.hint||"";$("#promptHint").classList.toggle("hidden",!q.hint);$("#kind").textContent=(q.isReview?"Wiederholung · ":"")+(KIND[q.type]||"");const tip=$("#grammarTip");tip.className="grammarTip"+(active&&active.grammar&&pos===0?"":" hidden");tip.innerHTML=active&&active.grammar?icon("bulb")+`<span>${esc(active.grammar)}</span>`:"";$("#feedback").className="feedback hidden";$("#sheet").className="actionSheet";$("#check").classList.remove("hidden");$("#next").classList.add("hidden");$("#check").disabled=true;const card=$(".lessonCard");card.classList.remove("shake","enter");void card.offsetWidth;card.classList.add("enter");card.dataset.type=q.type;const sp=$("#speak");sp.classList.toggle("hidden",!HAS_TTS||!SPEAK_BEFORE.includes(q.type));sp.onclick=()=>speak(q.spoken);const a=$("#answerArea");a.innerHTML="";if(document.activeElement&&document.activeElement!==document.body)document.activeElement.blur();if(q.type==="match")renderMatch(q,a);else if(q.type==="order")renderOrder(q,a);else if(q.options)renderChoices(q,a);else renderInput(q,a);if(q.type==="listen"||q.type==="listen-choice")setTimeout(()=>speak(q.spoken),300)}
function renderChoices(q,a){const list=document.createElement("div");list.className="choiceList"+(q.type==="odd"||q.type==="cloze"?" compact":"");shuffle(q.options).forEach((o,i)=>{const b=document.createElement("button");b.className="choice";b.dataset.value=o;b.innerHTML=`<kbd>${i+1}</kbd><span></span>`;b.lastChild.textContent=o;b.onclick=()=>{if(checked)return;answer=o;[...list.children].forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("#check").disabled=false};list.appendChild(b)});a.appendChild(list)}
function renderInput(q,a){const i=document.createElement("input");i.className="textInput";i.placeholder="Kroatische Antwort";i.autocomplete="off";i.autocapitalize="off";i.spellcheck=false;i.oninput=()=>{answer=i.value;$("#check").disabled=!norm(answer)};i.onkeydown=e=>{if(e.key!=="Enter")return;e.preventDefault();if(checked)goNext();else if(!$("#check").disabled)check()};const keys=document.createElement("div");keys.className="charKeys";["č","ć","đ","š","ž"].forEach(c=>{const b=document.createElement("button");b.type="button";b.textContent=c;b.onmousedown=e=>e.preventDefault();b.onclick=()=>{if(checked)return;const s=i.selectionStart??i.value.length,t=i.selectionEnd??s;i.value=i.value.slice(0,s)+c+i.value.slice(t);i.setSelectionRange(s+1,s+1);i.focus();i.oninput()};keys.appendChild(b)});a.append(i,keys);setTimeout(()=>i.focus(),50)}
function renderOrder(q,a){const line=document.createElement("div"),bank=document.createElement("div");line.className="orderLine";bank.className="wordBank";const sync=()=>{answer=[...line.children].map(x=>x.textContent).join(" ");$("#check").disabled=bank.children.length>0};q.words.forEach(w=>{const b=document.createElement("button");b.className="chip";b.textContent=w;b.onclick=()=>{if(checked)return;(b.parentNode===bank?line:bank).appendChild(b);sync()};bank.appendChild(b)});a.append(line,bank)}
function renderMatch(q,a){q.wrong=new Set();q.misses=0;let sel=null,done=0;const grid=document.createElement("div");grid.className="matchGrid";const cols={hr:document.createElement("div"),de:document.createElement("div")};Object.values(cols).forEach(c=>{c.className="matchCol";grid.appendChild(c)});["hr","de"].forEach(side=>shuffle(q.pairs.map((p,i)=>i)).forEach(i=>{const b=document.createElement("button");b.className="choice matchItem";b.textContent=q.pairs[i][side];b.onclick=()=>{if(checked||b.disabled)return;if(!sel||sel.side===side){if(sel)sel.b.classList.remove("selected");sel={side,i,b};b.classList.add("selected");if(side==="hr")speak(q.pairs[i].hr);return}const other=sel;sel=null;other.b.classList.remove("selected");if(other.i===i){[other.b,b].forEach(x=>{x.classList.add("matched");x.disabled=true});if(++done===q.pairs.length){answer="ok";$("#check").disabled=false;setTimeout(check,350)}}else{q.misses++;q.wrong.add(i);q.wrong.add(other.i);[other.b,b].forEach(x=>{x.classList.add("mismatch");setTimeout(()=>x.classList.remove("mismatch"),550)})}};cols[side].appendChild(b)}));a.appendChild(grid)}
function speak(t){if(!HAS_TTS||!t)return;const u=new SpeechSynthesisUtterance(t);u.lang="hr-HR";u.rate=.78;const v=speechSynthesis.getVoices().find(x=>x.lang.toLowerCase().startsWith("hr"));if(v)u.voice=v;speechSynthesis.cancel();speechSynthesis.speak(u)}
function retryFor(q){if(q.type==="odd")return null;if(q.type==="match"||q.type==="dialogue")return {...q};if(!q.item)return null;return ex(RECOG.includes(q.type)?"input-hr":"choice-hr",q.item)}
function check(){if(checked)return;checked=true;const q=queue[pos],fb=$("#feedback");let ok,near=false;if(q.type==="match")ok=q.wrong.size===0;else{ok=norm(answer)===norm(q.answer);if(!ok&&(q.type==="input-hr"||q.type==="listen")&&plain(answer)===plain(q.answer))ok=near=true}let title,text;state.total++;session.total++;state.daily.exercises++;if(ok){state.correct++;session.correct++;state.xp+=8;title=near?"Fast perfekt":pick(PRAISE);text=near?`Achte auf die Sonderzeichen: ${q.answer}`:"+8 XP"}else{title=q.type==="match"?"Geschafft, mit Umwegen":"Nicht ganz";text=q.type==="match"?`${q.misses>1?q.misses+" Fehlversuche":"Ein Fehlversuch"}. Die Paare kommen gleich noch einmal.`:`Richtig: ${q.type==="cloze"?q.answer+" – "+q.item.hr:q.type==="order"?q.item.hr:q.answer}`;const r=retryFor(q);if(r)queue.splice(Math.min(queue.length,pos+3),0,r)}if(q.type==="odd")text+="\n"+q.info.map(x=>`${x.hr} = ${x.de}`).join("\n");$("#fbTitle").textContent=title;$("#fbText").textContent=text;fb.querySelector("use").setAttribute("href",ok?"#i-check":"#i-close");fb.className="feedback "+(ok?"ok":"no");$("#sheet").className="actionSheet "+(ok?"ok":"no");if(!ok)$(".lessonCard").classList.add("shake");document.querySelectorAll("#answerArea .choice:not(.matchItem)").forEach(b=>{if(norm(b.dataset.value)===norm(q.answer))b.classList.add("correct");else if(b.classList.contains("selected"))b.classList.add("wrong")});const inp=$("#answerArea .textInput");if(inp){inp.readOnly=true;inp.classList.add(ok?"correct":"wrong")}const line=$("#answerArea .orderLine");if(line)line.classList.add(ok?"correct":"wrong");if(q.type==="dialogue"){state.daily.dialogues++;session.dialogues++}if(q.isReview||mode==="review"){state.daily.reviews++;session.reviews++}if(q.type==="match")q.pairs.forEach((p,i)=>p.key&&schedule(p.key,!q.wrong.has(i)));else if(q.key)schedule(q.key,ok);updateStreak();save();renderCommon();if(q.item&&HAS_TTS&&q.type!=="dialogue"){const sp=$("#speak");sp.classList.remove("hidden");sp.onclick=()=>speak(q.item.hr)}$("#check").classList.add("hidden");$("#next").classList.remove("hidden");$("#next").focus({preventScroll:true})}
function goNext(){if(!checked)return;pos++;renderQ()}
function finish(){state.studySeconds=(state.studySeconds||0)+Math.max(0,Math.round((Date.now()-session.start)/1000));let stars=0;if(active){if(!state.completed.includes(active.id)){state.completed.push(active.id);state.xp+=active.isTest?60:30}if(active.isTest){const rate=session.total?session.correct/session.total:0;stars=rate>=.9?3:rate>=.75?2:1;state.testStars[active.id]=Math.max(state.testStars[active.id]||0,stars)}}save();const pct=session.total?Math.round(session.correct/session.total*100):100;$("#doneTitle").textContent=pct>=90?"Odlično!":pct>=70?"Vrlo dobro!":"Samo naprijed!";$("#doneText").textContent=mode==="review"?"Deine fälligen Wiederholungen sind erledigt.":active&&active.isTest?"Kapiteltest bestanden. Das nächste Kapitel ist jetzt offen.":"Wortschatz, Hören und echte Situationen – ein Schritt weiter.";$("#doneScore").innerHTML=`<b>0</b><span>% direkt richtig<br>${session.correct} von ${session.total} Aufgaben</span>${active&&active.isTest?`<span class="stars" aria-label="${stars} von 3 Sternen">${[0,1,2].map(k=>icon("star",k<stars?"on":"")).join("")}</span>`:""}`;show("done");const m=$(".doneSteps");m.style.animation="none";void m.getBoundingClientRect();m.style.animation="";countUp($("#doneScore b"),pct)}
document.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>show(b.dataset.screen));$("#continueBtn").onclick=()=>startLesson((nextLesson()||{}).id);$("#levelBack").onclick=renderLevels;$("#reviewBtn").onclick=startReview;$("#practiceDue").onclick=startReview;$("#practiceWrong").onclick=startWrongPractice;$("#practiceRandom").onclick=startRandom;$("#practiceTests").onclick=showTests;$("#check").onclick=check;$("#next").onclick=goNext;addEventListener("keydown",e=>{if(!$("#lesson").classList.contains("active")||e.target.tagName==="INPUT")return;if(e.key==="Enter"){e.preventDefault();if(checked)goNext();else if(!$("#check").disabled)check()}else if(/^[1-5]$/.test(e.key)&&!checked){const b=document.querySelectorAll("#answerArea .choice:not(.matchItem)")[e.key-1];if(b)b.click()}});$("#close").onclick=()=>{if(active){show("levels");openLevel(active.level)}else show("practice")};addEventListener("resize",()=>{moveDock();clearTimeout(drawPaths.t);drawPaths.t=setTimeout(()=>drawPaths(false),120)});document.fonts&&document.fonts.ready.then(()=>{moveDock();drawPaths(false)});$("#homeBtn").onclick=()=>show("home");resetDaily();show("home");if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
